# -*- coding: utf-8 -*-
"""MLFinalProjectCodeManasaManya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAT2a6YJHIZegdK3kiy3_EQ3rf4NLURz
"""

import pandas as pd
url='https://raw.githubusercontent.com/manasa6sai/DepressionDetectionData/main/train_data.csv'
data = pd.read_csv(url, encoding='ISO-8859-1')
print(data)

data.isna().sum()

data.describe()

data['Label'].value_counts()

duplicates = data.duplicated(subset = 'Text data', keep = False)
print(duplicates)

data[duplicates].sort_values('PID')

data = data.drop_duplicates()

data.sort_values("Text data", inplace=True)
data.drop_duplicates(subset="Text data", keep=False, inplace=True)

data

data.describe()

import os
import gensim
import spacy
import spacy.cli

spacy.cli.download("en_core_web_lg")
nlp = spacy.load('en_core_web_lg')

pip install deep-translator

pip install googletrans==4.0.0-rc1

!pip install emoji
import emoji

data['Text data'] = data['Text data'].apply(lambda x: emoji.demojize(x))
print(data)

import re

def replace_emojis(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"  # chinese char
                               u"\U00002702-\U000027B0"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"  # dingbats
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

# Example usage
data['Text data'] = data['Text data'].apply(replace_emojis)

data

!pip install demoji

import demoji

# Download the emoji library
demoji.download_codes()

# Function to replace emojis with textual representations
def replace_emojis(text):
    return demoji.replace_with_desc(text)

# Apply the function to the 'Text data' column
data['Text data'] = data['Text data'].apply(replace_emojis)

# Print the modified DataFrame
print(data)

# Dictionary mapping emojis to their textual representations
emoji_mapping = {
    "😀": ":grinning_face:",
    "😁": ":beaming_face_with_smiling_eyes:",
    "😆": ":grinning_squinting_face:",
    "😅": ":grinning_face_with_sweat:",
    "😂": ":face_with_tears_of_joy:",
    "🤣": ":rolling_on_the_floor_laughing:",
    "😊": ":smiling_face_with_smiling_eyes:",
    "😇": ":smiling_face_with_halo:",
    "🙂": ":slightly_smiling_face:",
    "🙃": ":upside_down_face:",
    "😉": ":winking_face:",
    "😌": ":relieved_face:",
    "😍": ":smiling_face_with_heart_eyes:",
    "😘": ":face_blowing_a_kiss:",
    "😗": ":kissing_face:",
    "😚": ":kissing_face_with_closed_eyes:",
    "😙": ":kissing_face_with_smiling_eyes:",
    "🥰": ":smiling_face_with_hearts:",
    "😋": ":face_savoring_food:",
    "😛": ":face_with_tongue:",
    "😜": ":winking_face_with_tongue:",
    "😝": ":squinting_face_with_tongue:",
    "🤪": ":zany_face:",
    "🤨": ":face_with_raised_eyebrow:",
    "🧐": ":face_with_monocle:",
    "🤓": ":nerd_face:",
    "😎": ":smiling_face_with_sunglasses:",
    "🤩": ":star_struck:",
    "😏": ":smirking_face:",
    "😒": ":unamused_face:",
    "😞": ":disappointed_face:",
    "😔": ":pensive_face:",
    "😟": ":worried_face:",
    "😕": ":confused_face:",
    "🙁": ":slightly_frowning_face:",
    "☹️": ":frowning_face:",
    "😣": ":persevering_face:",
    "😖": ":confounded_face:",
    "😫": ":tired_face:",
    "😩": ":weary_face:",
    "🥺": ":pleading_face:",
    "😢": ":crying_face:",
    "😭": ":loudly_crying_face:",
    "😤": ":face_with_steam_from_nose:",
    "😠": ":angry_face:",
    "😡": ":pouting_face:",
    "🤬": ":face_with_symbols_on_mouth:",
    "🤯": ":exploding_head:",
    "😳": ":flushed_face:",
    "🥵": ":hot_face:",
    "🥶": ":cold_face:",
    "😱": ":face_screaming_in_fear:",
    "😨": ":fearful_face:",
    "😰": ":anxious_face_with_sweat:",
    "😥": ":sad_but_relieved_face:",
    "😓": ":face_with_cold_sweat:",
    "🤗": ":hugging_face:",
    "🤔": ":thinking_face:",
    "🤭": ":face_with_hand_over_mouth:",
    "🤫": ":shushing_face:",
    "🤥": ":lying_face:",
    "😶‍🌫️": ":face_in_clouds:",
    "😐": ":neutral_face:",
    "😑": ":expressionless_face:",
    "😬": ":grimacing_face:",
    "🙄": ":face_with_rolling_eyes:",
    "😯": ":hushed_face:",
    "😦": ":frowning_face_with_open_mouth:",
    "😧": ":anguished_face:",
    "😮": ":face_with_open_mouth:",
    "😲": ":astonished_face:",
    "😴": ":sleeping_face:",
    "🤤": ":drooling_face:",
    "😪": ":sleepy_face:",
    "😵": ":dizzy_face:",
    "🤐": ":zipper_mouth_face:",
    "🥴": ":woozy_face:",
    "🤢": ":nauseated_face:",
    "🤮": ":face_vomiting:",
    "🤧": ":sneezing_face:",
    "😷": ":face_with_medical_mask:",
    "🤒": ":face_with_thermometer:",
    "🤕": ":face_with_head_bandage:",
    "🤑": ":money_mouth_face:",
    "🤠": ":cowboy_hat_face:",
    "🥳": ":partying_face:",
    "🥸": ":disguised_face:",
    "😎": ":smiling_face_with_sunglasses:",
    "🤓": ":nerd_face:",
    "🧐": ":face_with_monocle:",
    "😕": ":confused_face:",
    "😟": ":worried_face:",
    "🙁": ":slightly_frowning_face:",
    "☹️": ":frowning_face:",
    "😮‍💨": ":face_exhaling:",
    "😮‍💨": ":face_in_clouds:",
    "😯‍": ":face_with_raised_eyebrow:",
    "😦‍": ":frowning_face_with_open_mouth:",
    "😧‍": ":anguished_face:",
    "😧‍": ":face_exhaling:",
    "😧‍": ":face_with_steam_from_nose:"

}

# Function to replace emojis with their textual representations
def replace_emojis(text):
    for emoji, desc in emoji_mapping.items():
        text = text.replace(emoji, desc)
        #print("##########")
    return text

# Apply the function to the 'Text data' column
data['Text data'] = data['Text data'].apply(replace_emojis)

# Print the modified DataFrame
#print(data)

!pip install unidecode

from unidecode import unidecode
data['Text data'] = data['Text data'].apply(lambda x: unidecode(x))
print(data)

pip install accelerate -U



import torch
from transformers import RobertaTokenizer, RobertaForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import pandas as pd


# Assuming your dataset has columns named "Text data" and "Label" for text and labels
texts = data['Text data'].values
labels = data['Label'].values

# Split data into train and test sets
train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

# Encode labels to numerical values
label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
test_labels = label_encoder.transform(test_labels)

# Load pre-trained RoBERTa model and tokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=len(label_encoder.classes_))

# Tokenize input texts
train_encodings = tokenizer(list(train_texts), truncation=True, padding=True)
test_encodings = tokenizer(list(test_texts), truncation=True, padding=True)

# Create PyTorch datasets
class DepressionDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = DepressionDataset(train_encodings, train_labels)
test_dataset = DepressionDataset(test_encodings, test_labels)

# Fine-tune the pre-trained RoBERTa model
training_args = TrainingArguments(
    output_dir='./results',  # output directory
    num_train_epochs=3,  # total number of training epochs
    per_device_train_batch_size=8,  # batch size per device during training
    per_device_eval_batch_size=8,   # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,  # strength of weight decay
    logging_dir='./logs',  # directory for storing logs
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

# Evaluate the model
eval_results = trainer.evaluate(eval_dataset=test_dataset)

# Print evaluation results
print("Evaluation results:")
print(eval_results)

# Predict and print classification report
preds = trainer.predict(test_dataset)
predicted_classes = label_encoder.inverse_transform(preds.predictions.argmax(axis=1))


# Convert predicted classes back to numerical format using label_encoder
predicted_numeric_classes = label_encoder.transform(predicted_classes)

# Print classification report
print(classification_report(test_labels, predicted_numeric_classes))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Assuming you have the actual labels and predicted labels stored in test_labels and predicted_classes respectively

# Compute confusion matrix
# Convert test_predicted_classes to integers if they are represented as strings
test_predicted_classes = label_encoder.transform(predicted_classes)

# Now you can compute the confusion matrix
cm = confusion_matrix(test_labels, test_predicted_classes)
# Plot confusion matrix heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, cmap='Blues', fmt='g', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.title('Confusion Matrix')
plt.show()